; US International Layout without Dead Keys
; Lower Case Letters
>!a:: Send "á"
>!c:: Send "©"
>!d:: Send "ð"
>!e:: Send "é"
>!l:: Send "ø"
>!m:: Send "µ"
>!n:: Send "ñ"
>!o:: Send "ó"
>!p:: Send "ö"
>!q:: Send "ä"
>!r:: Send "®"
>!s:: Send "ß"
>!t:: Send "þ"
>!u:: Send "ú"
>!w:: Send "å"
>!y:: Send "ü"
>!z:: Send "æ"

; Upper Case Letters
+>!a:: Send "Á"
+>!c:: Send "¢"
+>!d:: Send "Ð"
+>!e:: Send "É"
+>!l:: Send "Ø"
+>!n:: Send "Ñ"
+>!o:: Send "Ó"
+>!p:: Send "Ö"
+>!q:: Send "Ä"
+>!s:: Send "§"
+>!t:: Send "Þ"
+>!u:: Send "Ú"
+>!w:: Send "Å"
+>!y:: Send "Ü"
+>!z:: Send "Æ"

; Lower Case Digits
>!1:: Send "¡"
>!2:: Send "²"
>!3:: Send "³"
>!4:: Send "¤"
>!5:: Send "€"
>!6:: Send "¼"
>!7:: Send "½"
>!8:: Send "¾"
>!9:: Send "‘"
>!0:: Send "’"

; Upper Case Digits
+>!1:: Send "¹"
+>!4:: Send "£"

; Lower Misc Chars
>!-:: Send "¥"
>!=:: Send "×"
>![:: Send "«"
>!]:: Send "»"
>!\:: Send "¬"
>!;:: Send "¶"
>!':: Send "´"
>!,:: Send "ç"
>!/:: Send "¿"

; Upper Misc Chars
+>!=:: Send "÷"
+>!\:: Send "¦"
+>!;:: Send "°"
+>!':: Send "¨"
+>!,:: Send "Ç"
